Repository et-dagen/et-dagen, pull requests merged in 2023-08, with the labels that each got.

#38 Feature/34 setup ci for main branch
  .github/workflows/dev-branch.yml
  .github/workflows/lintfix.yml
  .github/workflows/staging-branch.yml
  composables/useFirebaseAuth.ts
  config/vuetify/vuetify.config.ts
  nuxt.config.ts
Labels: feature, help wanted, devops

#41 feat: user data server routes
  composables/useFirebaseAuth.ts
  middleware/auth.global.ts
  models/User.ts
  pages/index.vue
  plugins/auth.server.ts
  plugins/firebase.client.ts
  server/api/getAuth.ts
  server/api/user/index.delete.ts
  server/api/user/index.post.ts
  server/api/user/index.ts
  server/middleware/auth.ts
  server/middleware/user.ts
  server/utils/firebase.ts
  server/utils/formatFirebaseUser.ts
  server/utils/hasAccessLevel.ts
  utils/formatUser.ts
Labels: feature

#42 Feature/37 setup husky pre push and pre commit lintfix script to enforce code style
  .eslintignore
  .husky/pre-commit
  .prettierignore
  package-lock.json
  package.json
Labels: feature, good first issue

#53 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: good first issue

#54 fix: i18n
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/dev-branch.yml
  .prettierignore
  locales/en-US.json
  locales/nb-NO.json
  nuxt.config.ts
  package-lock.json
  package.json
  pages/index.vue
  pnpm-lock.yaml
Labels: bug, help wanted

#50 fix: changed workflow branch target, conditionals for pr approval job…
  .github/workflows/staging-branch.yml
Labels: bug, devops

#63 feat: access-level middleware
  layouts/default.vue
  middleware/auth.global.ts
  models/Meta.d.ts
  pages/@protected/admin.vue
  stores/authStore.ts
  tsconfig.json
Labels: feature

#68 fix: removed template-curly-spacing eslint-prettier rule as this was …
  .eslintrc.cjs
Labels: bug

#52 Fix/51 windows crlf v. lf linting
  .eslintrc.cjs
  .prettierrc.cjs
  package.json
Labels: bug

#69 refactor: move i18n.config.ts to config
  config/i18n.config.ts
  nuxt.config.ts
Labels: good first issue, refactor
