Repository et-dagen/et-dagen, pull requests merged in 2023-09, with the labels that each got.

#66 feat: nav menu
  .eslintrc.cjs
  app.vue
  assets/scss/main.scss
  components/nav/Button.vue
  components/nav/Buttons.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/user/Button.vue
  components/user/Menu.vue
  composables/useFirebaseAuth.ts
  config/vuetify/_defaults.ts
  layouts/default.vue
  locales/en-US.json
  locales/nb-NO.json
  middleware/auth.global.ts
  models/Nav.ts
  nuxt.config.ts
  pages/@protected/protected.vue
  pages/[...slug].vue
  pages/admin.vue
  pages/admin/companies.vue
  pages/admin/events.vue
  pages/admin/jobs.vue
  pages/admin/sponsors.vue
  pages/admin/users.vue
  pages/contact.vue
  pages/index.vue
  pages/jobs.vue
  pages/jobs/[job].vue
  pages/jobs/index.vue
  pages/program.vue
  pages/program/[event].vue
  pages/program/index.vue
  pages/user.vue
  pages/user/index.vue
  pages/user/login.vue
  pages/user/signup.vue
  public/favicon.ico
  public/images/logo.png
  stores/appStore.ts
Labels: feature

#72 feat: custom error page
  error.vue
  pages/[...slug].vue
Labels: feature

#86 refactor: access levels and user types
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  composables/useFirebaseAuth.ts
  middleware/auth.global.ts
  models/Meta.d.ts
  models/User.ts
  pages/admin.vue
  server/api/user/index.delete.ts
  server/api/user/index.post.ts
  server/api/user/index.ts
  server/utils/hasAccess.ts
  server/utils/hasAccessLevel.ts
  stores/appStore.ts
  stores/authStore.ts
Labels: refactor

#73 feat: locale switcher
  components/locale/Switcher.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/user/Menu.vue
  nuxt.config.ts
  public/images/flags/en.svg
  public/images/flags/no.svg
Labels: feature, good first issue

#80 feat: banner component
  app.vue
  assets/scss/main.scss
  components/home/Banner.vue
  composables/useDate.ts
  locales/en-US.json
  locales/nb-NO.json
  models/DateTime.ts
  nuxt.config.ts
  pages/index.vue
  pnpm-lock.yaml
Labels: feature, help wanted

#98 feat: company api endpoints
  components/nav/Button.vue
  components/nav/Buttons.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/user/StateButton.vue
  error.vue
  models/User.ts
  pages/[...slug].vue
  pages/admin.vue
  pages/user/index.vue
  pages/user/signin.vue
  server/api/company/index.delete.ts
  server/api/company/index.post.ts
  server/api/company/index.put.ts
  server/api/company/index.ts
Labels: feature
