Repository et-dagen/et-dagen, pull requests merged in 2023-11, with the labels that each got.

#103 feat: companycard component
  components/company/Card.vue
  pages/index.vue
Labels: feature, good first issue

#120 feat: admin panel layout
  app.vue
  assets/scss/main.scss
  assets/scss/settings.scss
  components/admin/CategoryButton.vue
  components/company/Card.vue
  components/locale/Switcher.vue
  components/nav/Button.vue
  components/nav/Buttons.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/user/Menu.vue
  components/user/StateButton.vue
  config/vuetify/_defaults.ts
  config/vuetify/_themes.ts
  layouts/default.vue
  locales/en-US.json
  locales/nb-NO.json
  nuxt.config.ts
  pages/admin.vue
  pages/admin/sponsors.vue
  pages/admin/users.vue
  pages/index.vue
  pages/user/signin.vue
  pages/user/signup.vue
  plugins/loading.ts
  server/utils/formatFirebaseUser.ts
  stores/appStore.ts
Labels: feature

#110 feat: program Timeline component
  components/home/Banner.vue
  components/program/Timeline.vue
  composables/useAlerts.ts
  composables/useDate.ts
  composables/useEvent.ts
  composables/useTime.ts
  locales/en-US.json
  locales/nb-NO.json
  models/DateTime.ts
  pages/program/index.vue
  server/api/event/index.ts
  server/api/event/register/[eventUID].delete.ts
  server/api/event/register/[eventUID].post.ts
Labels: feature

#96 feat: companycardgrid component
  components/company/Grid.Vue
  pages/index.vue
Labels: feature

#108 feat: contactcard component
  assets/scss/main.scss
  components/contact/Card.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/contact.vue
Labels: feature

#129 feat: dynamic company rendering
  components/company/Card.vue
  components/company/Grid.vue
  components/user/SigninForm.vue
  components/user/SignupForm.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/index.vue
Labels: styling

#126 feat: user list in admin panel
  assets/scss/main.scss
  components/admin/CategoryButton.vue
  components/company/Hero.vue
  components/form/EmailInput.vue
  components/form/PasswordInput.vue
  components/form/SelectInput.vue
  components/form/TextInput.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/user/SigninForm.vue
  components/user/SignupForm.vue
  config/app.config.ts
  config/vuetify/_defaults.ts
  layouts/default.vue
  locales/en-US.json
  locales/nb-NO.json
  models/User.ts
  nuxt.config.ts
  package.json
  pages/admin.vue
  pages/admin/users.vue
  pages/event/edit/index.vue
  pnpm-lock.yaml
  server/api/user/index.delete.ts
Labels: feature
