Repository et-dagen/et-dagen, pull requests merged in 2023-12, with the labels that each got.

#128 feat: dynamically rendering of study programmes
  components/user/SignupForm.vue
  server/api/programme/index.ts
Labels: feature

#162 feat: adding responsive footer component
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  assets/scss/main.scss
  components/footer/Index.vue
  layouts/default.vue
  locales/en-US.json
  locales/nb-NO.json
  public/images/logo_long_neg.png
Labels: feature

#158 feat: containerise for production
  .dockerignore
  Dockerfile
Labels: feature, devops, priority

#166 feat: create job api endpoints
  locales/en-US.json
  server/api/event/index.post.ts
  server/api/event/index.put.ts
  server/api/job/index.delete.ts
  server/api/job/index.post.ts
  server/api/job/index.put.ts
  server/api/job/index.ts
Labels: feature, help wanted

#175 feat: adding favicons
  nuxt.config.ts
  public/images/favicon-light.ico
  public/images/favicon.ico
Labels: feature, help wanted

#145 feat: smaller contact card for grid
  components/common/Grid.vue
  components/contact/Card.vue
  components/contact/GridCard.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/contact.vue
Labels: feature

#167 fix: omit render of email icon on md breakpoint and lower
  components/footer/Index.vue
Labels: feature

#183 docs: updating README
  README.md
Labels: documentation, refactor

#178 fix: changing main sponsor to main partner
  pages/index.vue
Labels: bug, help wanted, refactor

#185 feat: remove user from event
  components/program/Timeline.vue
  composables/useAlerts.ts
  locales/en-US.json
  locales/nb-NO.json
  server/api/event/register/index.delete.ts
  server/api/event/register/index.post.ts
Labels: feature, refactor

#181 fix: PROD support for firebase admin credentials
  .env.example
  server/utils/firebase.ts
Labels: bug, help wanted, devops, priority

#124 feat: Event listing for administration
  components/program/Timeline.vue
  composables/useEvent.ts
  locales/en-US.json
  locales/nb-NO.json
  models/Event.ts
  pages/admin/events.vue
  pnpm-lock.yaml
  public/favicon.ico
Labels: feature

#157 fix: overlapping sections on landing page
  components/company/Hero.vue
Labels: bug
