Repository et-dagen/et-dagen, pull requests merged in 2024-01, with the labels that each got.

#194 refactor: verbose firebase-admin auth certificate
  nuxt.config.ts
  server/utils/firebase.ts
Labels: bug, devops, priority

#195 Deploy test
  components/company/Hero.vue
  nuxt.config.ts
  server/utils/firebase.ts
Labels: devops

#196 Fix/193 refactor production env variables for firebase admin sdk
  server/utils/firebase.ts
Labels: devops, priority

#197 Deploy test
  server/utils/firebase.ts
Labels: devops

#214 Fix/refactor env variables
  .gitignore
  nuxt.config.ts
  package.json
Labels: devops, priority

#216 refactor: refactor configuration of env variables
  .env.example
  nuxt.config.ts
  plugins/firebase.client.ts
  server/utils/firebase.ts
Labels: devops, priority

#191 feat: Edit company list
  components/common/Grid.vue
  components/company/Card.vue
  components/company/EditForm.vue
  components/company/Hero.vue
  components/form/FileInput.vue
  components/form/NumberInput.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/company/edit/[id].vue
  pages/company/edit/index.vue
  pages/index.vue
  server/api/company/index.delete.ts
  server/api/company/index.post.ts
  server/api/image/index.post.ts
  server/utils/firebase.ts
Labels: feature, help wanted

#109 feat: CountDown component
  components/form/SelectInput.vue
  components/form/TextInput.vue
  components/home/CountDown.vue
  composables/useDateTime.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/index.vue
  server/api/event/index.delete.ts
  server/api/event/index.post.ts
  server/api/event/index.put.ts
  server/api/programme/index.ts
Labels: feature

#245 feat: job admin page
  config/app.config.ts
  locales/en-US.json
  locales/nb-NO.json
  models/Job.ts
  pages/admin/jobs.vue
  server/api/job/index.post.ts
Labels: feature, refactor, priority

#249 feat: User allergy registration
  components/user/SignupForm.vue
  composables/useFirebaseAuth.ts
  config/app.config.ts
  locales/en-US.json
  locales/nb-NO.json
  server/api/user/index.post.ts
Labels: feature, refactor, priority

#164 refactor: homebanner to companyhero format
  components/home/Banner.vue
  pages/index.vue
Labels: refactor, priority

#252 feat: jobs overview page
  components/job/Card.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/jobs/index.vue
Labels: feature

#258 fix: missing selected class on program tabs
  components/programme/Timeline.vue
Labels: feature

#259 fix: add target blank to event map link
  components/programme/Timeline.vue
Labels: feature

#262 fix: active class on nav btn
  config/app.config.ts
  locales/en-US.json
  locales/nb-NO.json
Labels: bug

#264 refactor: concise mobile actions
  components/job/Card.vue
  components/programme/Timeline.vue
  pages/event/[id].vue
Labels: feature, styling, refactor

#265 feat: job page
  locales/en-US.json
  locales/nb-NO.json
  pages/jobs/[id].vue
  pages/jobs/[job].vue
Labels: feature

#267 feat: static page title
  nuxt.config.ts
Labels: feature, priority

#271 feat: user page
  locales/en-US.json
  locales/nb-NO.json
  models/User.ts
  pages/user/index.vue
Labels: feature

#282 feat: etdagene options in event edit
  components/event/EditForm.vue
Labels: feature, priority

#283 feat: date time input
  components/event/EditForm.vue
  components/form/DateTimeInput.vue
  components/job/EditForm.vue
  composables/useDate.ts
Labels: feature, priority

#292 fix: import types with type
  components/locale/Switcher.vue
  components/user/EditForm.vue
  package.json
  pnpm-lock.yaml
Labels: bug, priority

#296 refactor: month string in timeline tab
  components/home/Banner.vue
  components/job/Card.vue
  components/programme/Timeline.vue
  composables/useDate.ts
  pages/jobs/[id].vue
Labels: refactor, priority

#295 refactor: footer component
  components/footer/Index.vue
Labels: refactor

#287 feat: job application link
  components/job/Card.vue
  components/job/EditForm.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/admin/jobs.vue
  pages/jobs/[id].vue
  pages/user/index.vue
  server/api/job/index.post.ts
Labels: feature

#299 feat: company event info
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/job/EditForm.vue
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/programme/Timeline.vue
  components/user/EditForm.vue
  composables/useDate.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/company/admin.vue
  pages/user/edit/index.vue
  server/api/company/events/index.ts
  server/api/user/index.ts
Labels: feature, refactor, priority

#277 feat: event signup and optout deadline
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/job/EditForm.vue
  components/user/SigninForm.vue
  components/user/SignupForm.vue
  composables/useAlerts.ts
  composables/useTime.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
  pages/user/edit/[id].vue
  pages/user/edit/index.vue
  server/api/event/index.post.ts
  server/api/event/index.put.ts
  server/api/event/register/index.delete.ts
  server/api/event/register/index.post.ts
  server/utils/useTime.ts
Labels: feature, refactor, priority

#289 feat: card grid
  components/common/Grid.vue
  components/company/Card.vue
  components/company/Grid.vue
Labels: bug, priority

#301 refactor: company admin nav
  components/nav/Horizontal.vue
  components/nav/Vertical.vue
  components/programme/Timeline.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/admin/events.vue
Labels: refactor

#300 feat: index page styling
  components/company/Hero.vue
  components/home/CountDown.vue
  pages/index.vue
Labels: good first issue, styling

#304 chore: format to string in tab
  components/programme/Timeline.vue
Labels: refactor, priority

#309 fix: don't display user info if company user
  pages/user/index.vue
Labels: bug

#307 fix: conditional render of registration start display
  pages/event/[id].vue
Labels: bug

#311 fix: adding capacity to existing event
  components/event/EditForm.vue
Labels: bug

#313 fix: date tab sorting
  components/programme/Timeline.vue
Labels: bug, priority
