Repository et-dagen/et-dagen, pull requests merged in 2024-02, with the labels that each got.

#320 Deploy fixes
  README.md
  components/event/EditForm.vue
  components/programme/Timeline.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
  pages/user/index.vue
Labels: bug, devops

#324 fix: 323 force allergy input on custom
  components/user/EditForm.vue
  components/user/SignupForm.vue
  config/app.config.ts
  locales/en-US.json
  locales/nb-NO.json
Labels: bug, refactor, priority

#329 feat: styling adjustments on home page
  components/common/Grid.vue
  components/home/CountDown.vue
  pages/index.vue
Labels: bug, styling

#330 fix: weird locale switcher color behaviour
  components/locale/Switcher.vue
  public/images/board/business.jpg
  public/images/board/deputy_manager.jpg
  public/images/board/finance.jpg
  public/images/board/it.jpg
  public/images/board/logistics.jpg
  public/images/board/manager.jpg
  public/images/board/marketing.jpg
  public/images/board/sponsor.jpg
  public/images/board/travel.jpg
  public/images/logo_long.png
Labels: bug, styling

#328 fix: jobs page panicking when no jobs
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/job/EditForm.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/admin.vue
  pages/admin/companies.vue
  pages/admin/events.vue
  pages/admin/jobs.vue
  pages/jobs/index.vue
Labels: bug

#332 feat: event restrictions
  components/event/EditForm.vue
  components/user/SignupForm.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
  server/api/event/register/index.post.ts
Labels: feature, priority

#336 Deploy changes
  components/common/Grid.vue
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/home/CountDown.vue
  components/job/EditForm.vue
  components/locale/Switcher.vue
  components/programme/Timeline.vue
  components/user/EditForm.vue
  components/user/SignupForm.vue
  config/app.config.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/admin.vue
  pages/admin/companies.vue
  pages/admin/events.vue
  pages/admin/jobs.vue
  pages/event/[id].vue
  pages/index.vue
  pages/jobs/index.vue
  public/images/board/business.jpg
  public/images/board/deputy_manager.jpg
  public/images/board/finance.jpg
  public/images/board/it.jpg
  public/images/board/logistics.jpg
  public/images/board/manager.jpg
  public/images/board/marketing.jpg
  public/images/board/sponsor.jpg
  public/images/board/travel.jpg
  public/images/logo_long.png
  server/api/event/register/index.post.ts
Labels: devops

#342 refactor: rich text support for description
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/form/RichTextInput.vue
  components/job/Card.vue
  components/job/EditForm.vue
  locales/en-US.json
  locales/nb-NO.json
  package.json
  pages/event/[id].vue
  pages/jobs/[id].vue
  pnpm-lock.yaml
Labels: feature, help wanted, refactor, priority

#348 feat: confirm event opt out
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
Labels: feature, priority

#346 feat: add event list to user page
  assets/scss/main.scss
  locales/en-US.json
  locales/nb-NO.json
  pages/user/index.vue
Labels: feature

#355 feat: keepalive pages
  app.vue
Labels: feature

#354 feet: add some links in the footer
  components/footer/Index.vue
  locales/en-US.json
  locales/nb-NO.json
Labels: feature

#339 refactor: new alert system
  app.vue
  components/common/Alert.vue
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/job/EditForm.vue
  components/user/EditForm.vue
  components/user/SigninForm.vue
  components/user/SignupForm.vue
  composables/useAlerts.ts
  composables/useTranslation.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
  server/api/code/index.delete.ts
  server/api/code/index.post.ts
  server/api/code/index.ts
  server/api/company/events/index.ts
  server/api/company/index.delete.ts
  server/api/company/index.post.ts
  server/api/company/index.put.ts
  server/api/event/index.delete.ts
  server/api/event/index.post.ts
  server/api/event/index.put.ts
  server/api/event/register/index.delete.ts
  server/api/event/register/index.post.ts
  server/api/image/index.post.ts
  server/api/job/index.delete.ts
  server/api/job/index.post.ts
  server/api/job/index.put.ts
  server/api/user/index.delete.ts
  server/api/user/index.post.ts
  server/api/user/index.put.ts
  server/api/user/index.ts
  server/api/user/signout.post.ts
  stores/alertStore.ts
Labels: feature, refactor

#360 feat: job card nuxtlink
  components/job/Card.vue
Labels: feature

#363 Deploy changes
  app.vue
  components/common/Alert.vue
  components/company/EditForm.vue
  components/event/EditForm.vue
  components/footer/Index.vue
  components/job/Card.vue
  components/job/EditForm.vue
  components/user/EditForm.vue
  components/user/SigninForm.vue
  components/user/SignupForm.vue
  composables/useAlerts.ts
  composables/useDate.ts
  composables/useTranslation.ts
  locales/en-US.json
  locales/nb-NO.json
  pages/event/[id].vue
  server/api/code/index.delete.ts
  server/api/code/index.post.ts
  server/api/code/index.ts
  server/api/company/events/index.ts
  server/api/company/index.delete.ts
  server/api/company/index.post.ts
  server/api/company/index.put.ts
  server/api/event/index.delete.ts
  server/api/event/index.post.ts
  server/api/event/index.put.ts
  server/api/event/register/index.delete.ts
  server/api/event/register/index.post.ts
  server/api/image/index.post.ts
  server/api/job/index.delete.ts
  server/api/job/index.post.ts
  server/api/job/index.put.ts
  server/api/user/index.delete.ts
  server/api/user/index.post.ts
  server/api/user/index.put.ts
  server/api/user/index.ts
  server/api/user/signout.post.ts
  stores/alertStore.ts
Labels: devops

#369 feat: i18n banner slogan
  locales/en-US.json
  locales/nb-NO.json
  pages/index.vue
Labels: feature, i18n

#370 feat: user email in company admin
  locales/en-US.json
  locales/nb-NO.json
  pages/company/admin.vue
Labels: feature, i18n

#367 default sorting order for jobs
  pages/jobs/index.vue
Labels: refactor

#372 fix: deprecated alert system for user/edit
  components/company/EditForm.vue
  components/user/EditForm.vue
  locales/en-US.json
  locales/nb-NO.json
  pages/user/signin.vue
Labels: bug, refactor, priority

#368 edit event in place
  components/form/RichTextInput.vue
  pages/event/[id].vue
  pages/jobs/[id].vue
Labels: feature

#375 fix: keep alive
  app.vue
  package.json
  pages/jobs/index.vue
  pages/programme.vue
  pnpm-lock.yaml
Labels: bug
